version: "3"

networks:
  boxbilling-network:

services:
  # nginx-landing:
  #   build:
  #     context: .
  #     dockerfile: nginx-landing.dockerfile
  #   container_name: nginx-landing
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./src:/var/www/html
  #     - ./config/default.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - boxbilling-network

  mysql:
    image: mysql:5.7.33
    container_name: mysql_boxbilling
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: boxbilling
      MYSQL_USER: foo
      MYSQL_PASSWORD: foo
      MYSQL_ROOT_PASSWORD: foo
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - boxbilling-network
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql

  docker-boxbilling:
    build:
      context: .
      dockerfile: docker-boxbilling.dockerfile
    container_name: docker-boxbilling
    ports:
      - "8004:8080"
    networks:
      - boxbilling-network
    depends_on:
      - mysql

  myapp:
    image: docker.io/bitnami/codeigniter:3
    container_name: landingpage_ku
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    depends_on:
      - mysql
    networks:
      - boxbilling-network

  # mariadb:
  #   image: docker.io/bitnami/mariadb:10.3
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   networks:
  #     - boxbilling-network
